### ISSUE TITLE
Errors when tax not found in taxdump

### ISSUE THREAD

**Issue by tanaes** [SamStudio8/ktkit#4]
Running Reticulatus, and encountering the following error in ktkit:

```
[WARN] Taxon ID 1109743 not found in NCBI Dump
Traceback (most recent call last):
  File "/home/jgs286/miniconda3/envs/reticulatus/bin/ktkit", line 8, in <module>
    sys.exit(cli())
  File "/home/jgs286/miniconda3/envs/reticulatus/lib/python3.6/site-packages/ktkit/__init__.py", line 162, in cli
    modes[args.mode](args)
  File "/home/jgs286/miniconda3/envs/reticulatus/lib/python3.6/site-packages/ktkit/__init__.py", line 84, in read_file
    fields.append(cache_map[old_tax][0].replace(' ', '_'))
AttributeError: 'int' object has no attribute 'replace'
```

It appears that this is due to the return of `(tid, tid)` in that case here: 

https://github.com/tanaes/ktkit/blob/24f4896c5b920f3485153dd38eb49f2eadd8c8f1/ktkit/__init__.py#L15-L17

**Comment by SamStudio8** [comment]
Hi Jon,
Thanks for this. I've had an offline report from a user bumping into this same issue but it looks like I forgot to push the fix upstream.
I'll pull your patch now.
